# tasks file for network-interfaces
---
- name: create directory
  file:
    path: "{{ network_interfaces_interface_path }}"
    state: directory
  when: network_interfaces_interfaces | length > 0
  tags:
    - configuration
    - network-interfaces
    - network-interfaces-create-directory

- name: all interfaces
  template:
    src: etc/network/interfaces.j2
    dest: "{{ network_interfaces_all_interfaces_path }}"
  notify: network all interfaces changed
  when: network_interfaces_interfaces | length > 0
  tags:
    - configuration
    - network-interfaces
    - network-interfaces-all-interfaces

- name: list network interfaces
  command: "find {{ network_interfaces_interface_path }} -type f"
  changed_when: false
  when: network_interfaces_interfaces | length > 0
  register: network_interfaces_existing_files
  tags:
    - configuration
    - network-interfaces
    - network-interfaces-list-network-interfaces

- name: configurations
  template:
    src: etc/network/interfaces.d/device.j2
    dest: "{{ network_interfaces_interface_path }}/device-{{ item.device }}-{{ item.family | default('inet') }}"
  with_items: network_interfaces_interfaces
  register: network_interfaces_configuration_result
  notify:
    - network restart interface service
    - network restart interface command
  tags:
    - configuration
    - network-interfaces
    - network-interfaces-configurations

- include: manage_devices.yml
  when: network_interfaces_manage_devices

# TODO: use this to restart interfaces that are active
#- name: list active interfaces
#  command: "cat {{ network_interface_states_path }}"
#  changed_when: no
#  when: network_configuration_result.changed
#  register: network_active_interfaces
